### ISSUE TITLE
File not found- svg path

### ISSUE THREAD

**Issue by T3xtM4rk3r** [arc2qgis/qlyrx#13]
Hello,

first of all I would like to congratulate you for this really awesome plugin! 
In converted a bunch of lyrx files already, but one file gives me some trouble.
The following error is issued when i try to convert it:

2021-10-19T10:42:35     WARNING    Traceback (most recent call last):
              File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1526, in run
              self.apply_lyrx_symbols(layer, j_data, geometry_general_type_str)
              File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1304, in apply_lyrx_symbols
             picture_ret = self.parsePictureFill(symbol_def, svg_file_appendix)
              File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1081, in parsePictureFill
              template_f = open(plugin_path+'/img/svg_template.svg')
             FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SD\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qlyrx/img/svg_template.svg'

I checked the input .lyrx file and the one symbology value leading to the error is of the "type" : "CIMPictureFill".
If i remove this value in ArcGIS and export the new lyrx file, the qlyrx plugin works just fine.

**Comment by bogind** [comment]
Wow,
thanks for pointing this out, it seems I accidentally deleted that folder a year ago and nobody noticed or reported.
please try using [v0.3.3](https://github.com/arc2qgis/qlyrx/releases/tag/v0.3.3), 
I just replaced the file there and the file that was uploaded to the QGIS plugins main repository.

If installing v0.3.3 fixes this for you we can call this problem solved.

**Comment by T3xtM4rk3r** [comment]
Hi,
thanks for your quick response.
Using the v0.3.3 version the conversion finished whithout any error.

Unfortunately it seem that the style conversion still fails, because from a
beige background with black dots in arcgis a white background with black dots in qgis emerges. 
A python warning is issued with 

2021-10-19T13:06:25     WARNING    warning:C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py:773: DeprecationWarning: an integer is required (got type float). Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
              new_color = QColor.fromRgb(color_array[0],color_array[1], color_array[2], opacity)
             
             traceback: File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1613, in run
              self.apply_lyrx_symbols(layer, self.j_data, geometry_general_type_str)
              File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 1380, in apply_lyrx_symbols
              ret_arr = self.parseSolidFill(symbol_def, layer)
              File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 517, in parseSolidFill
              new_color = self.colorToRgbArray(temp_color, ls['color']['type'])
              File "C:\Users/SD/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qlyrx\qlyrx.py", line 773, in colorToRgbArray
              new_color = QColor.fromRgb(color_array[0],color_array[1], color_array[2], opacity)

But thats probably another issue ;)
